name: Deploy GoDoc to GitHub Pages

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - .github/workflows/godoc.yml
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wow-look-at-my/static-pkgsite-action@v1

      - uses: actions/upload-artifact@v4
        with:
          name: godoc-site
          path: _site
          overwrite: true

      - name: Archive pages artifact
        if: github.ref == 'refs/heads/master'
        run: tar --dereference --hard-dereference --directory _site -cf $RUNNER_TEMP/artifact.tar --exclude=.git --exclude=.github .

      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error
          overwrite: true

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
